name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.sha }}
      - uses: actions/checkout@master
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: raptorhq/cloudflared-tunnel-kubectl@v1
        name: Deploy to cluster
        env:
          cloudflared_service_token_id: ${{ secrets.TOKEN_ID }}
          cloudflared_service_token_secret: ${{ secrets.TOKEN_SECRET }}
          cloudflared_host_address: 'k8s.mrln.link'
          kubeconfig: ${{ secrets.KUBECONFIG }}
          kubectl_args: set image deploy/eli-web eli-web=ghcr.io/${{ github.repository }}:${{ github.sha }}
